# Generated by Django 4.0.1 on 2022-01-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=1000)),
                ('Image', models.CharField(max_length=255)),
                ('HeaderImage', models.CharField(max_length=255)),
                ('Introduction', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('LastMod', models.DateField(default='2022-01-19 15:48:08')),
                ('Language', models.CharField(max_length=255)),
                ('KeyWords', models.CharField(max_length=255)),
                ('State', models.IntegerField()),
                ('NumVisit', models.IntegerField()),
                ('IdTheme', models.IntegerField()),
                ('IdUser', models.IntegerField()),
                ('IdHost', models.IntegerField()),
            ],
        ),
    ]
