# Generated by Django 4.0.1 on 2022-01-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEndAPI', '0006_alter_articles_lastmod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='LastMod',
            field=models.DateField(default='19 January 2022'),
        ),
    ]
